package fia.ues.edu.sv.domain;
// Generated 09-nov-2016 0:58:20 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Actividades generated by hbm2java
 */
@Entity
@Table(name="actividades"
    ,schema="public"
)
public class Actividades  implements java.io.Serializable {


     private int idactividades;
     private BigDecimal ponderacion;
     private String nombreactividad;
     private Set<Nota> notas = new HashSet<Nota>(0);
     private Set<Materia> materias = new HashSet<Materia>(0);

    public Actividades() {
    }

	
    public Actividades(int idactividades) {
        this.idactividades = idactividades;
    }
    public Actividades(int idactividades, BigDecimal ponderacion, String nombreactividad, Set<Nota> notas, Set<Materia> materias) {
       this.idactividades = idactividades;
       this.ponderacion = ponderacion;
       this.nombreactividad = nombreactividad;
       this.notas = notas;
       this.materias = materias;
    }
   
     @Id 

    
    @Column(name="idactividades", unique=true, nullable=false)
    public int getIdactividades() {
        return this.idactividades;
    }
    
    public void setIdactividades(int idactividades) {
        this.idactividades = idactividades;
    }

    
    @Column(name="ponderacion", precision=3)
    public BigDecimal getPonderacion() {
        return this.ponderacion;
    }
    
    public void setPonderacion(BigDecimal ponderacion) {
        this.ponderacion = ponderacion;
    }

    
    @Column(name="nombreactividad", length=50)
    public String getNombreactividad() {
        return this.nombreactividad;
    }
    
    public void setNombreactividad(String nombreactividad) {
        this.nombreactividad = nombreactividad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="actividades")
    public Set<Nota> getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set<Nota> notas) {
        this.notas = notas;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="materia_tiene_actividades", schema="public", joinColumns = { 
        @JoinColumn(name="idactividades", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idmateria", nullable=false, updatable=false) })
    public Set<Materia> getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Set<Materia> materias) {
        this.materias = materias;
    }




}


