package fia.ues.edu.sv.domain;
// Generated 09-nov-2016 0:58:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estudiante generated by hbm2java
 */
@Entity
@Table(name="estudiante"
    ,schema="public"
)
public class Estudiante  implements java.io.Serializable {


     private int idestudiante;
     private Grado grado;
     private String nombreestudiante;
     private String apelllidosestudiante;
     private String nie;
     private Set<Nota> notas = new HashSet<Nota>(0);

    public Estudiante() {
    }

	
    public Estudiante(int idestudiante) {
        this.idestudiante = idestudiante;
    }
    public Estudiante(int idestudiante, Grado grado, String nombreestudiante, String apelllidosestudiante, String nie, Set<Nota> notas) {
       this.idestudiante = idestudiante;
       this.grado = grado;
       this.nombreestudiante = nombreestudiante;
       this.apelllidosestudiante = apelllidosestudiante;
       this.nie = nie;
       this.notas = notas;
    }
   
     @Id 

    
    @Column(name="idestudiante", unique=true, nullable=false)
    public int getIdestudiante() {
        return this.idestudiante;
    }
    
    public void setIdestudiante(int idestudiante) {
        this.idestudiante = idestudiante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idgrado")
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }

    
    @Column(name="nombreestudiante", length=60)
    public String getNombreestudiante() {
        return this.nombreestudiante;
    }
    
    public void setNombreestudiante(String nombreestudiante) {
        this.nombreestudiante = nombreestudiante;
    }

    
    @Column(name="apelllidosestudiante", length=30)
    public String getApelllidosestudiante() {
        return this.apelllidosestudiante;
    }
    
    public void setApelllidosestudiante(String apelllidosestudiante) {
        this.apelllidosestudiante = apelllidosestudiante;
    }

    
    @Column(name="nie", length=8)
    public String getNie() {
        return this.nie;
    }
    
    public void setNie(String nie) {
        this.nie = nie;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set<Nota> getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set<Nota> notas) {
        this.notas = notas;
    }




}


