package fia.ues.edu.sv.domain;
// Generated 09-nov-2016 0:58:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grado generated by hbm2java
 */
@Entity
@Table(name="grado" ,schema="public")
public class Grado  implements java.io.Serializable {


     private int idgrado;
     private Character grado;
     private Character seccion;
     private String descripciongrado;
     private Set<Docente> docentes = new HashSet<Docente>(0);
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

    public Grado() {
    }

	
    public Grado(int idgrado) {
        this.idgrado = idgrado;
    }
    public Grado(int idgrado, Character grado, Character seccion, String descripciongrado, Set<Docente> docentes, Set<Estudiante> estudiantes) {
       this.idgrado = idgrado;
       this.grado = grado;
       this.seccion = seccion;
       this.descripciongrado = descripciongrado;
       this.docentes = docentes;
       this.estudiantes = estudiantes;
    }
   
     @Id 

    
    @Column(name="idgrado", unique=true, nullable=false)
    public int getIdgrado() {
        return this.idgrado;
    }
    
    public void setIdgrado(int idgrado) {
        this.idgrado = idgrado;
    }

    
    @Column(name="grado", length=1)
    public Character getGrado() {
        return this.grado;
    }
    
    public void setGrado(Character grado) {
        this.grado = grado;
    }

    
    @Column(name="seccion", length=1)
    public Character getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Character seccion) {
        this.seccion = seccion;
    }

    
    @Column(name="descripciongrado", length=20)
    public String getDescripciongrado() {
        return this.descripciongrado;
    }
    
    public void setDescripciongrado(String descripciongrado) {
        this.descripciongrado = descripciongrado;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="docentes_imparten_a_grados", schema="public", joinColumns = { 
        @JoinColumn(name="idgrado", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="iddocente", nullable=false, updatable=false) })
    public Set<Docente> getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set<Docente> docentes) {
        this.docentes = docentes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grado")
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }




}


