package fia.ues.edu.sv.domain;
// Generated 09-nov-2016 0:58:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Materia generated by hbm2java
 */
@Entity
@Table(name="materia"
    ,schema="public"
)
public class Materia  implements java.io.Serializable {


     private int idmateria;
     private String nombremateria;
     private Set<Docente> docentes = new HashSet<Docente>(0);
     private Set<Actividades> actividadeses = new HashSet<Actividades>(0);
     private Set<Nota> notas = new HashSet<Nota>(0);

    public Materia() {
    }

	
    public Materia(int idmateria) {
        this.idmateria = idmateria;
    }
    public Materia(int idmateria, String nombremateria, Set<Docente> docentes, Set<Actividades> actividadeses, Set<Nota> notas) {
       this.idmateria = idmateria;
       this.nombremateria = nombremateria;
       this.docentes = docentes;
       this.actividadeses = actividadeses;
       this.notas = notas;
    }
   
     @Id 

    
    @Column(name="idmateria", unique=true, nullable=false)
    public int getIdmateria() {
        return this.idmateria;
    }
    
    public void setIdmateria(int idmateria) {
        this.idmateria = idmateria;
    }

    
    @Column(name="nombremateria", length=50)
    public String getNombremateria() {
        return this.nombremateria;
    }
    
    public void setNombremateria(String nombremateria) {
        this.nombremateria = nombremateria;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="materias")
    public Set<Docente> getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set<Docente> docentes) {
        this.docentes = docentes;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="materias")
    public Set<Actividades> getActividadeses() {
        return this.actividadeses;
    }
    
    public void setActividadeses(Set<Actividades> actividadeses) {
        this.actividadeses = actividadeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="materia")
    public Set<Nota> getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set<Nota> notas) {
        this.notas = notas;
    }




}


