package fia.ues.edu.sv.domain;
// Generated 09-nov-2016 0:58:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Periodo generated by hbm2java
 */
@Entity
@Table(name="periodo"
    ,schema="public"
)
public class Periodo  implements java.io.Serializable {


     private int idperiodo;
     private Integer numeroperiodo;
     private String mes;
     private String ano;
     private Set<Nota> notas = new HashSet<Nota>(0);

    public Periodo() {
    }

	
    public Periodo(int idperiodo) {
        this.idperiodo = idperiodo;
    }
    public Periodo(int idperiodo, Integer numeroperiodo, String mes, String ano, Set<Nota> notas) {
       this.idperiodo = idperiodo;
       this.numeroperiodo = numeroperiodo;
       this.mes = mes;
       this.ano = ano;
       this.notas = notas;
    }
   
     @Id 

    
    @Column(name="idperiodo", unique=true, nullable=false)
    public int getIdperiodo() {
        return this.idperiodo;
    }
    
    public void setIdperiodo(int idperiodo) {
        this.idperiodo = idperiodo;
    }

    
    @Column(name="numeroperiodo")
    public Integer getNumeroperiodo() {
        return this.numeroperiodo;
    }
    
    public void setNumeroperiodo(Integer numeroperiodo) {
        this.numeroperiodo = numeroperiodo;
    }

    
    @Column(name="mes", length=30)
    public String getMes() {
        return this.mes;
    }
    
    public void setMes(String mes) {
        this.mes = mes;
    }

    
    @Column(name="ano", length=4)
    public String getAno() {
        return this.ano;
    }
    
    public void setAno(String ano) {
        this.ano = ano;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="periodo")
    public Set<Nota> getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set<Nota> notas) {
        this.notas = notas;
    }




}


