package fia.ues.edu.sv.domain;
// Generated 09-nov-2016 0:58:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name="rol"
    ,schema="public"
)
public class Rol  implements java.io.Serializable {


     private int idrol;
     private String descripcionrol;
     private String nombrerol;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Rol() {
    }

	
    public Rol(int idrol) {
        this.idrol = idrol;
    }
    public Rol(int idrol, String descripcionrol, String nombrerol, Set<Usuario> usuarios) {
       this.idrol = idrol;
       this.descripcionrol = descripcionrol;
       this.nombrerol = nombrerol;
       this.usuarios = usuarios;
    }
   
     @Id 

    
    @Column(name="idrol", unique=true, nullable=false)
    public int getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(int idrol) {
        this.idrol = idrol;
    }

    
    @Column(name="descripcionrol", length=50)
    public String getDescripcionrol() {
        return this.descripcionrol;
    }
    
    public void setDescripcionrol(String descripcionrol) {
        this.descripcionrol = descripcionrol;
    }

    
    @Column(name="nombrerol", length=25)
    public String getNombrerol() {
        return this.nombrerol;
    }
    
    public void setNombrerol(String nombrerol) {
        this.nombrerol = nombrerol;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rol")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


